package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWages<M extends BaseWages<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public void setCarno(java.lang.String carno) {
		set("carno", carno);
	}
	
	public java.lang.String getCarno() {
		return getStr("carno");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}
	
	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setBank(java.lang.String bank) {
		set("bank", bank);
	}
	
	public java.lang.String getBank() {
		return getStr("bank");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setMonth(java.lang.String month) {
		set("month", month);
	}
	
	public java.lang.String getMonth() {
		return getStr("month");
	}

}
